# Hyperledger Composer Developers Guide
- [Introduction](./introduction.md)
- [Using Online Playground](./onlineplayground.md)
- [Setting up a Local development environment](./localdev.md)
- [Creating Models](./models.md)
- [Writing TP Functions](./tpfunctions.md)
- [Writing Queries](./queries.md)
- [Writing ACLs](./acls.md)
- [Writing Unit tests for business networks](./unittests.md)
- [Writing Client Applications](./clientapps.md)
- [Writing Angular Applications](./angularapps.md)
- [Utilising a standalone runtime server](./simulator.md)
- [Utilising a real Fabric](./realfabric.md)
- [REST API](./restapi.md)
- [Testing events with Node-Red](./nodered.md)
- [Using Fabric API in TP Functions](./fabricapi.md)
- [External models](./externalmodels.md)

